title: Empresa de ventas de Videojuegos 
iconURL: assets/default-icon.png
theme: jekyll-theme-time-machine

# for a clean URL
permalink: :slug

footer-link:
  email: santosn1235@gmail.com
  github: Joel199822

plugins:
 - jekyll-feed
 - jekyll-seo-tag

### comments & analytics
hyvor_talk_website_id: 14
google_analytics: UA-NNNNNNNN-N
